CHAT_MODEL_NAME = "gpt-4o-mini"
CHAT_MODEL_TEMPERATURE = 0.5
CHAT_MODEL_MAX_TOKENS = 950

MAX_FETCH_LENGTH = 650 * 1024
MIN_DATA_LENGTH = 62

MAX_INTERACTIONS = 4

COOKIE_DURATION = 16 * 60 * 60

MONGO_CONNECTION_TIMEOUT = 3000
MONGO_DB_NAME = "synthetic_data_db"
MONGO_COL_NAME = "synthetic_data_col"

S3_UPLOAD_FOLDER = "synthetic_data_generation"
